spring.application.name=order-service
server.port=8082

services.customer.base-url=${CUSTOMER_SERVICE_URL:http://localhost:8081}
services.notification.base-url=${NOTIFICATION_SERVICE_URL:http://localhost:8083}

management.endpoints.web.exposure.include=health,info
