name: Dynamically Build and Push Microservice Images

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  # --------------------------------------------------
  # JOB 1: Discover every service having a Dockerfile
  # --------------------------------------------------

  discover-services:
    runs-on: ubuntu-latest

    outputs:
      services: ${{ steps.discover.outputs.services }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Discover services
        id: discover
        shell: bash
        run: |
          SERVICES=$(find services -mindepth 2 -maxdepth 2 -name Dockerfile -print0 | xargs -0 -n1 dirname | xargs -n1 basename | jq -R -s -c 'split("\n")[:-1]')

          echo "Discovered services:"
          echo "$SERVICES"

          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"


  # --------------------------------------------------
  # JOB 2: Build every discovered service
  # --------------------------------------------------

  build-and-push:

    needs:
      - discover-services

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        service: ${{ fromJson(needs.discover-services.outputs.services) }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Prepare image information
        id: image-info
        shell: bash
        run: |
          CURRENT_VERSION=$(mvn help:evaluate \
            -Dexpression=project.version \
            -q \
            -DforceStdout)
      
          BASE_VERSION=${CURRENT_VERSION%-SNAPSHOT}
      
          UPDATED_VERSION="${BASE_VERSION}-${{ github.run_number }}"
      
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
      
          echo "version=$UPDATED_VERSION" >> "$GITHUB_OUTPUT"
          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"
      
          echo "Version: $UPDATED_VERSION"
          echo "SHA: $SHORT_SHA"
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4


      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v7
        with:
          build-args: |
            BUILD_TYPE=release
            VERSION=${{ steps.image-info.outputs.version }}
          context: .
          file: services/${{ matrix.service }}/Dockerfile
          push: true

          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:sha-${{ steps.image-info.outputs.short_sha }}-${{ steps.image-info.outputs.version }}

          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service }}
